// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsvFeFVkjLlJUmlGnmnelRXKNWNmK07zI',
    appId: '1:148585222424:web:42e0a3714f5a6848e34e6d',
    messagingSenderId: '148585222424',
    projectId: 'pizza-delivery-21c79',
    authDomain: 'pizza-delivery-21c79.firebaseapp.com',
    storageBucket: 'pizza-delivery-21c79.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB8v5sxyuxE75pT1ngUB_GFB7rZNBmRvY',
    appId: '1:148585222424:android:b516ecb77be29bd4e34e6d',
    messagingSenderId: '148585222424',
    projectId: 'pizza-delivery-21c79',
    storageBucket: 'pizza-delivery-21c79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATseSOZ4zmM1fvYOgiTbDjgjG0Tg9V5R4',
    appId: '1:148585222424:ios:be15f6eeda55e48ee34e6d',
    messagingSenderId: '148585222424',
    projectId: 'pizza-delivery-21c79',
    storageBucket: 'pizza-delivery-21c79.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATseSOZ4zmM1fvYOgiTbDjgjG0Tg9V5R4',
    appId: '1:148585222424:ios:be15f6eeda55e48ee34e6d',
    messagingSenderId: '148585222424',
    projectId: 'pizza-delivery-21c79',
    storageBucket: 'pizza-delivery-21c79.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsvFeFVkjLlJUmlGnmnelRXKNWNmK07zI',
    appId: '1:148585222424:web:96a1552bbc5d21f0e34e6d',
    messagingSenderId: '148585222424',
    projectId: 'pizza-delivery-21c79',
    authDomain: 'pizza-delivery-21c79.firebaseapp.com',
    storageBucket: 'pizza-delivery-21c79.appspot.com',
  );

}